name: 'Telegram Message Notify'
description: 'Sending a Telegram message'
author: 'razz1k'
inputs:
  GITHUB_REPO:
    description: 'GITHUB_REPO'
  GITHUB_RUN_ID:
    description: 'GITHUB_RUN_ID'
  TG_BOT_TOKEN:
    description: 'token for telegram bot'
    default: "1"
  TG_CHAT_ID:
    description: 'the chat ID that will receive the message'
    default: "1"
  TG_TOPIC_ID:
    description: 'the topic of the chat ID that will receive the message'
    default: "1"
  GITHUB_RUNNER_TOKEN:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.


      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.


      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  NEEDS:
    description: 'include only jobs info from job.needs'
    default: ''
runs:
  using: node20
  main: main.js

