name: 'Telegram Message Notify'

on:
  workflow_call:
    inputs:
      GITHUB_REPO:
        required: true
        type: string
      GITHUB_RUN_ID:
        required: true
        type: string
    secrets:
      TG_BOT_TOKEN:
        required: true
      TG_CHAT_ID:
        required: true
      GITHUB_RUNNER_TOKEN:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: send msg
        run: |
          GITHUB_REPO="${{ inputs.GITHUB_REPO }}" \
          GITHUB_RUN_ID="${{ inputs.GITHUB_RUN_ID }}" \
          TG_BOT_TOKEN="${{ secrets.TG_BOT_TOKEN }}" \
          TG_CHAT_ID="${{ secrets.TG_CHAT_ID }}" \
          GITHUB_RUNNER_TOKEN="${{ secrets.GITHUB_RUNNER_TOKEN }}" \
          node main.js
